############## Created by de.microtema:github-workflow-maven-plugin ############
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
# Files under .github/workflows folder are generated and should not be edited. #
################################################################################

name: '[DEV] Azure Serverless Architecture with Terraform'
on:
  push:
    branches:
      - develop
env:
  APP_NAME: "azure-serverless"
  APP_DISPLAY_NAME: "Azure Serverless Architecture with Terraform"
  VERSION: "1.0.0-SNAPSHOT"
  STAGE_NAME: "dev"
  NODE_VERSION: "16"
  NAMESPACE: "microtema-dev-westeurope-01"
  AZURE_LOCATION: "westeurope"
jobs:
  compile:
    name: Initialize
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm install
  security-check:
    name: Security Check
    runs-on: [ ubuntu-latest ]
    needs: [ compile ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'NPM: security-check'
        run: npm run security-check
  unit-test:
    name: Unit Test
    runs-on: [ ubuntu-latest ]
    needs: [ compile ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'NPM: test'
        run: npm test
  build:
    name: Build
    runs-on: [ self-hosted ]
    needs: [ compile ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'NPM: build'
        run: npm run build
  promote:
    name: Promote
    runs-on: [ ubuntu-latest ]
    needs: [ build ]
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'
      - name: Check Resource Group
        id: rg-check
        run: echo "exists=$(az group exists -n rg-$NAMESPACE)" >> $GITHUB_OUTPUT
      - name: Create Resource Group
        if: steps.rg-check.outputs.exists == 'false'
        run: |
          az group create \
          --location $AZURE_LOCATION \
          --name rg-$NAMESPACE
      - name: Wait Resource Group
        if: steps.rg-check.outputs.exists == 'false'
        run: |
          az group wait --created  \
           --resource-group rg-$NAMESPACE
      - name: Create Storage Account
        if: steps.rg-check.outputs.exists == 'false'
        run: |
          az storage account create \
          --name ${NAMESPACE//[^[:alnum:]]/""} \
          --resource-group rg-$NAMESPACE
      - name: Create Storage Container
        if: steps.rg-check.outputs.exists == 'false'
        run: |
          az storage container create \
          --name scm-releases \
          --resource-group rg-$NAMESPACE \
          --account-name ${NAMESPACE//[^[:alnum:]]/""}
  deployment:
    name: Deployment
    runs-on: [ ubuntu-latest ]
    needs: [ promote ]
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET}}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID}}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Node: Setup'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: 'NPM: install azure-functions-cli'
        run: npm i -g azure-functions-cli
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform Init
        working-directory: ./terraform
        run: |
          terraform init \
            -backend-config="resource_group_name=rg-$NAMESPACE" \
            -backend-config="storage_account_name=${NAMESPACE//[^[:alnum:]]/""}"
      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate
      - name: Terraform Plan
        working-directory: ./terraform
        run: |
          terraform plan -out=tfplan \
            -input=false \
            -var-file="env/.$STAGE_NAME.tfvars"
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply tfplan