############## Created by de.microtema:github-workflow-maven-plugin ############
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
# Files under .github/workflows folder are generated and should not be edited. #
################################################################################

name: '[DEV] Azure Serverless Architecture with Terraform'
on:
  push:
    branches:
      - develop
env:
  APP_NAME: "azure-serverless"
  APP_DISPLAY_NAME: "Azure Serverless Architecture with Terraform"
  VERSION: "1.0.0-SNAPSHOT"
  STAGE_NAME: "dev"
  NODE_VERSION: "16"
  NAMESPACE: "microtema-dev-westeurope-01"
  AZURE_LOCATION: "westeurope"
jobs:
  initialize:
    name: Initialize
    runs-on: [ ubuntu-latest ]
    needs: [ ]
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'
      - name: Check Resource Group
        id: rg-check
        run: echo "exists=$(az group exists -n rg-$NAMESPACE)" >> $GITHUB_OUTPUT
      - name: Create Resource Group
        if: steps.rg-check.outputs.exists == 'false'
        run: |
          az group create \
          --location $AZURE_LOCATION \
          --name rg-$NAMESPACE
      - name: Wait Resource Group
        if: steps.rg-check.outputs.exists == 'false'
        run: |
          az group wait --created  \
           --resource-group rg-$NAMESPACE
      - name: Create Storage Account
        if: steps.rg-check.outputs.exists == 'false'
        run: |
          az storage account create \
          --name ${NAMESPACE//-/} \
          --resource-group rg-$NAMESPACE
      - name: Create Storage Container
        if: steps.rg-check.outputs.exists == 'false'
        run: |
          az storage container create \
          --name scm-releases \
          --resource-group rg-$NAMESPACE \
          --account-name ${NAMESPACE//-/}
  deployment:
    name: Deployment
    runs-on: [ ubuntu-latest ]
    needs: [ initialize ]
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET}}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID}}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform Init
        working-directory: ./terraform
        run: |
          terraform init \
            -backend-config="resource_group_name=rg-$NAMESPACE" \
            -backend-config="storage_account_name=${NAMESPACE//-/}"
      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate
      - name: Terraform Plan
        working-directory: ./terraform
        run: |
          terraform plan -out=tfplan \
            -input=false \
            -var-file="env/.$STAGE_NAME.tfvars"
      - name: Terraform Apply
        working-directory: ./terraform
        run: echo terraform apply tfplan