############## Created by de.microtema:github-workflow-maven-plugin ############
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
# Files under .github/workflows folder are generated and should not be edited. #
################################################################################

name: '[DEV] Azure Serverless Architecture with Terraform'
on:
  push:
    branches:
      - develop
env:
  APP_NAME: "azure-serverless"
  APP_DISPLAY_NAME: "Azure Serverless Architecture with Terraform"
  VERSION: "1.0.0-SNAPSHOT"
  STAGE_NAME: "dev"
  NODE_VERSION: "16"
  NAMESPACE: "microtema-dev-westeurope-08"
  AZURE_LOCATION: "westeurope"
jobs:
  initialize:
    name: Initialize
    runs-on: [ ubuntu-latest ]
    needs: [ ]
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Check Resource Group
        id: rg-check
        run: echo "exists=$(az group exists -n rg-$NAMESPACE)" >> $GITHUB_OUTPUT
      - name: Create Resource Group
        if: steps.rg-check.outputs.exists == 'false'
        run: |
          az group create \
          --location $AZURE_LOCATION \
          --name rg-$NAMESPACE
      - name: Wait Resource Group
        if: steps.rg-check.outputs.exists == 'false'
        run: |
          az group wait --created  \
           --resource-group rg-$NAMESPACE
      - name: Create Storage Account
        if: steps.rg-check.outputs.exists == 'false'
        run: |
          az storage account create \
          --name ${NAMESPACE//-/} \
          --resource-group rg-$NAMESPACE
      - name: Create Storage Container
        if: steps.rg-check.outputs.exists == 'false'
        run: |
          az storage container create \
          --name scm-releases \
          --resource-group rg-$NAMESPACE \
          --account-name ${NAMESPACE//-/}
  deployment:
    name: Deployment
    runs-on: [ ubuntu-latest ]
    needs: [ initialize ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Setup Azure
        run: |
          echo "ARM_CLIENT_ID=$(az ad sp list --display-name CICD --query '[0].appId')" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=~Xx8Q~fAkGUc8q2VBezCLZS2mPTgm560w4zUscsq" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$(az ad sp list --display-name CICD --query '[0].appOwnerOrganizationId')" >> $GITHUB_ENV
          echo "ARM_RG_ID=$(az group show --name rg-$NAMESPACE --query id)" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${ARM_RG_ID:15:36}" >> $GITHUB_ENV
          
          echo ARM_CLIENT_ID=${{ env.ARM_CLIENT_ID }}
          echo ARM_CLIENT_SECRET=${{ env.ARM_CLIENT_SECRET }}
          echo ARM_TENANT_ID=${{ env.ARM_TENANT_ID }}
          echo ARM_RG_ID=${{ env.ARM_RG_ID }}
          echo ARM_SUBSCRIPTION_ID=${{ env.ARM_SUBSCRIPTION_ID }}
      - name: Terraform Init
        working-directory: ./terraform
        run: |
          terraform init \
            -backend-config="resource_group_name=rg-$NAMESPACE" \
            -backend-config="storage_account_name=${NAMESPACE//-/}"
      - name: Terraform Validate
        working-directory: ./terraform
        run: echo terraform validate
      - name: Terraform Plan
        working-directory: ./terraform
        run: echo terraform plan -out=tfplan -input=false -var-file="env/.dev.tfvars"
      - name: Terraform Apply
        working-directory: ./terraform
        run: echo terraform apply tfplan